### ISSUE TITLE
❔ Querying API with Domain

### ISSUE THREAD

**Issue by ollyhensby** [buildingSMART/bSDD#100]
**Question**
Is there a way to query the [BSDD API](https://app.swaggerhub.com/apis/buildingSMART/Dictionaries/v1) to filter on a Domain e.g. [IfcBuildingControlsDomain](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/ifcbuildingcontrolsdomain/content.html)?

For reference, here are all the domains on the IFC documentation: https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/chapter-7/

**Comment by atomczak** [comment]
no, there is no information about IFC domains in the bSDD. IFC standard/documentation is the go to place for IFC details.
