### ISSUE TITLE
bSDD GraphQL schema 

### ISSUE THREAD

**Issue by ESiham** [buildingSMART/bSDD#24]
Hello everyone,
To get the bSDD GraphQL schema, I used the following CLI tool [get-graphql-schema](https://github.com/prisma-labs/get-graphql-schema), so I got the attached schema, but unfortunately, I couldn't find any filter or resolvers used.
My question is there is any ambition to add those filters and resolvers? 
[bSDD_schema.txt](https://github.com/buildingSMART/bSDD/files/7176673/bSDD_schema.txt)

**Comment by Baars-IT** [comment]
Hi ESiham,

Adding filters and resolvers was not on our backlog yet.
I've added them just now, but must discuss the priority of it.
Can you explain your use case for requesting filters and resolvers?

Thanks!
Erik

**Comment by ESiham** [comment]
Hello @Baars-IT, 
First, sorry for the late reply,
One of my use cases is:
 When I want to query a specific domain, firstly I should send  a query to know all the  available domains by extracting their names and their namespace URI as following:
`{
domains{
  name
namespaceUri
}}`
So it's quite long, but if we can do it like this it will be more efficient 
`{
  domains(filter:{uri:"IFC"}){
    ....
Here my processing
    ....
  }
}`
This is just one case, we can also add filters for the other types 😋
Thanks
Siham

**Comment by atomczak** [comment]
latest REST API has filters
