### ISSUE TITLE
How to search for a classification just by a specific attribute ?

### ISSUE THREAD

**Issue by ESiham** [buildingSMART/bSDD#25]
Hello,
Is there no possibility to search for a classification just by its "name" attribute or other specific attributes; for example, return just classifications that contain in their names the text that I put for the parameter searchText? 
because when I type the following command: 

`{domain(namespaceUri : 'http://identifier.buildingsmart.org/uri/etim/etim-8.0') {
    classificationSearch(searchText: 'cotter', languageCode: 'EN') {
      name
      definition
      synonyms
      namespaceUri
      properties{
        name
      }
    }
  }
}
`

I see that the search is  extended to the level of all attributes of the classification, and in this example: it is "synonyms", this is the result that I got:

`{
  "data": {
    "domain": {
      "classificationSearch": [
        {
          "name": "Split-/safe pin",
          "definition": null,
          "synonyms": [
            "Cotter key",
            "Cotter pin",
            "Double spring cotter",
            "Dowel pin",
            "Safe pin",
            "Slotted pin",
            "Split pin",
            "Spring connector",
            "Spring cotter",
            "Straight pin"
          ],
          "namespaceUri": "http://identifier.buildingsmart.org/uri/etim/etim-8.0/class/EC003020",
          "properties": [
            {
              "name": "Model"
            },
            {
              "name": "Material"
            },
            {
              "name": "Material quality"
            },
            {
              "name": "Surface protection"
            },
            {
              "name": "Diameter"
            },
            {
              "name": "Diameter axle"
            },
            {
              "name": "Length"
            }
          ]
        },
        {
          "name": "Assortment box fastening material",
          "definition": null,
          "synonyms": [
            "Assortment box fixation material",
            "Disc assortment",
            "Linch pin assortment",
            "Lubricating nipple assortment",
            "Plasterboard fixing assortment",
            "Range of rivets",
            "Splint assortment",
            "Spring cotter pin selection",
            "Spring cotter pin set",
            "Spring pin assortment",
            "Spring washer selection",
            "Spring washer set",
            "Srew and plug assortment",
            "Yacht assortment"
          ],
          "namespaceUri": "http://identifier.buildingsmart.org/uri/etim/etim-8.0/class/EC012002",
          "properties": [
            {
              "name": "Model"
            },
            {
              "name": "Number of sections"
            },
            {
              "name": "Number of screws"
            },
            {
              "name": "Number of dowels/plugs"
            },
            {
              "name": "Number of nuts"
            },
            {
              "name": "Number of washers"
            },
            {
              "name": "Number of rivets"
            },
            {
              "name": "Number of parts"
            },
            {
              "name": "With hand riveter"
            },
            {
              "name": "With transparent cover"
            },
            {
              "name": "With carrying handle"
            },
            {
              "name": "Length"
            },
            {
              "name": "Width"
            },
            {
              "name": "Height"
            }
          ]
        }
      ]
    }
  }
}`

Thanks.

**Comment by Baars-IT** [comment]
Hi Esiham,

This request is slowly bubbling to the top of our backlog :-)
I have an additional question: do you want to search the name field only with exact matches (ignoring case) or should it also search for partly matches?
