### ISSUE TITLE
GraphQL - non-nullable field symbol - unit

### ISSUE THREAD

**Issue by lemoinet** [buildingSMART/bSDD#27]
When we want to retrieve all units via this query:
```
query{
  units{
    name
    code
    symbol
  }
}
```
we get this error:
```
{
  "": [
    "Cannot return null for non-null type. Field: symbol, Type: String!."
  ]
}
```

The field symbol is now defined as a non-nullable field.
```
type Unit {
  code: String!
  name: String!
  symbol: String!
}
```
Is it possible to make this a nullable field since the symbols are almost always null?

**Comment by Baars-IT** [comment]
Thanks for letting us know, is fixed now!
