### ISSUE TITLE
Importing properties require Classifications

### ISSUE THREAD

**Issue by lemoinet** [buildingSMART/bSDD#28]
When I want to import only properties, I get the error that 'Classifications' must not be empty.
Isn't it possible to upload only properties in bsDD without the need to define classifications?

Example file
`{
  "OrganizationCode": "BBRI",
  "DomainCode": "BBRI",
  "DomainVersion": "0.1",
  "DomainName": "BBRI",
  "Status": "Preview",
  "DomainNamespaceUri": "http://identifier.buildingsmart.org/uri/BBRI/BBRI-0.1",
  "LanguageIsoCode": "EN",
  "Properties": [
    {
      "Code": "τv",
      "OwnedUri": "",
      "Uid": "",
      "Name": "Light transmittance",
      "Definition": "Fraction of the transmitted light by the incident light",
      "Status": "Active",
      "ActivationDateUtc": "2022-04-05",
      "RevisionDateUtc": null,
      "VersionDateUtc": "2022-04-05",
      "DeActivationDateUtc": null,
      "VersionNumber": null,
      "RevisionNumber": null,
      "ReplacedObjectCodes": [],
      "ReplacingObjectCodes": [], 
      "DeprecationExplanation": "",
      "CreatorLanguageIsoCode": "",
      "VisualRepresentationUri": "",
      "CountriesOfUse": [],
      "SubdivisionsOfUse": [],
      "CountryOfOrigin": "",
      "DocumentReference": "EN 410:2011",
      "Description": "",
      "Example": "",
      "ConnectedPropertyCodes": [],
      "PhysicalQuantity": "without",
      "Dimension": "",
      "DimensionLength": 0,
      "DimensionMass": 0,
      "DimensionTime": 0,
      "DimensionElectricCurrent": 0,
      "DimensionThermodynamicTemperature": 0,
      "DimensionAmountOfSubstance": 0,
      "DimensionLuminousIntensity": 0,
      "MethodOfMeasurement": "",
      "DataType": "Real",
      "PropertyValueKind": "Single",
      "MinInclusive": 0,
      "MaxInclusive": 1,
      "MinExclusive": null,
      "MaxExclusive": null,
      "Pattern": "",
      "IsDynamic": false,
      "DynamicParameterPropertyCodes": [],
      "Units": [],
      "AllowedValues": [],
      "TextFormat": ""
    }
  ],
  "Materials": []
}
`

**Comment by atomczak** [comment]
Each data dictionary needs to have at least one class. It could be a class of type GroupOfProperties, or other.
