### ISSUE TITLE
Member "PropertyKind" not found

### ISSUE THREAD

**Issue by lemoinet** [buildingSMART/bSDD#29]
In the [bsdd-import-model.json](https://github.com/buildingSMART/bSDD/blob/master/Model/Import%20Model/bsdd-import-model.json) file there is a member "PropertyKind" mentioned but when importing this error appears:

`Error - Error during import: Could not find member 'PropertyKind' on object of type 'ImportProperty'. `

Rename member "PropertyKind" to "PropertyValueKind" in [bsdd-import-model.json](https://github.com/buildingSMART/bSDD/blob/master/Model/Import%20Model/bsdd-import-model.json)

**Comment by Baars-IT** [comment]
Thanks for letting us know! And apology for this very late response :-(.

The bsdd-import-model.json file has been updated.
