### ISSUE TITLE
Update IFC classification names CSV

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/bSDD#30]
Shouldn't this list ([ifc-classification-names](https://github.com/buildingSMART/bSDD/blob/0ba28b3556032b1e6262d66b6f89b72889b6368b/Model/Import%20Model/reference-lists/ifc-classification-names.csv)) be updated to the new IFC4.3 schema?

**Comment by Baars-IT** [comment]
Hi Evandro,

Yes, you are correct, but I think I remove it completely. The list of names that are available can be retrieved via the (domain) API and then you have always the most up-to-date list.

**Comment by Baars-IT** [comment]
It now references the api:
https://api.bsdd.buildingsmart.org/api/Domain/v2/Classifications?namespaceUri=http%3A%2F%2Fidentifier.buildingsmart.org%2Furi%2Fbuildingsmart%2Fifc-4.3
