### ISSUE TITLE
Import: JSON schema and documentation are not congruent

### ISSUE THREAD

**Issue by araccaine** [buildingSMART/bSDD#33]
**Describe the bug**
[bSDD JSON import model.md](https://github.com/buildingSMART/bSDD/blob/dbacccba9202b208e6151ec9d52835b3682e5029/Model/Import%20Model/bSDD%20JSON%20import%20model.md) and [bsdd-import-model.json](https://github.com/buildingSMART/bSDD/blob/master/Model/Import%20Model/bsdd-import-model.json) are not congruent: the last chapter `PropertyRelation type` is missing in the JSON schema.

**Expected behavior**
Every described key in bSDD JSON import model.md should also exist in bsdd-import-model.json definition.

**Comment by Baars-IT** [comment]
Thanks for noting!
I checked the json and a few more items were missing.
It should be fixed now.
