### ISSUE TITLE
GET method to retriev all properties of a domain. 

### ISSUE THREAD

**Issue by MatthiasWeise** [buildingSMART/bSDD#35]
**Is your feature request related to a problem? Please describe.**
We would like to check properties of a particular domain in order to find similar definitions. Those properties should be shown as a list so that the user can browse through the list, e.g. if he/she wants to see existing definitions without using a particular search query. 

**Describe the solution you'd like**
We suggest to add an api call to retrieve all properties of domain, similar to classifications. The call could be:
`GET /api/Domain/v1/Properties`

**Describe alternatives you've considered**

1. checking properties for each classification -> results in many api calls, which would slow down performance 

2. using a search query requires at least 3 characters as search string (GET /api/TextSearchListOpen/v5). It is not clear if three wild cards could used as a work around (***), but results will not return all expected results (test with Swagger and IFC4.3)

**Additional context**
Feature is needed by buildingSMART Germany for support of extension groups working on own content to be published in bSDD as own domain, ideally linked with existing content (via Classification- and PropertyRelation).

**Comment by rasso** [comment]
The report on the Survey "The Role of openBIM in the Regulatory Process" ([https://www.buildingsmart.org/industry-survey-the-role-of-openbim-in-the-regulatory-process/](url) indictes cleary, that language matters. Language is not only the mother tongue but especcially the terms beeing used in the context of openBIM processes and in this context in procurement, contracts, exchange requirements, ... Existing and even competing calssification systems with their properties must continue to exist because legacy data would otherwise lose their validity. Mapping of classifications and their properties therefore is unavoidable. Everyone, how has to deal with this, will run into the same challange, which the buildingSMART Germany is facing, currently. Therefore, I support this feature request and urge its implementation.

**Comment by koberste75** [comment]
That feature would allow all connecting systems to make use of the already existing data in the bSDD. It enables the re-use of already defined properties in an easy and user-friendly way. I think this will be a huge benefit for software systems that support the users in seting up definitions for particular projects or working groups. I strongly support this request.

**Comment by mirbekbekboliev** [comment]
This solution could also be beneficial not only for chapters but also to bSI Rooms. Within the Building Room, there are various projects, which also targeted to publish their content on bSDD. Thus, we strongly recommend and endorse this feature request to be accepted. Moreover, it would enhance harmonization works, which are vital for all domains.

**Comment by Baars-IT** [comment]
Sorry for this late response but this feature is high on our backlog

**Comment by MatthiasWeise** [comment]
A short update after further discussion with bSI/Léon. Feature request has not been accepted for the time being (response with backlog was somehow confusing). The following alternatives have been proposed:

> 1. The first, most recommended, and used by all your competitors, is just using the normal API where you iterate over the classes to get the properties. The performance of the bSDD is very good; it runs on azure and is highly optimized for this. Performance is not an issue to ignore this option.
> 2. The second is to use the ‘requestdownload’ call to get a full XML of a domain. We have the option to fine tune that specifically for bimQ if you want. This call is made for this kind of software specific customization. 
> 3. Only the third option is to use GraphQL. It gives massive flexibility and you can use it for any kind of custom use-case. For your use-case you probably need some introspection setup. 

We have checked those alternatives and all are coming with shortcomings for our use case where we are trying to avoid caching of property definitions. At the end of the day we either have to make our own copy or use 3 letter-based search by user.  

1. Iteration over all entities is, as expected, quite slow due to communication overhead. According to our measurements we can fetch around 180 entities per minutes (after increasing server side query limit from 20 to 600 queries per minute). IFC4.3 is coming with ~1600 class definitions, which means ~9 min response time. 
2. Fetching full XML requires a special account - not usable with free/anonymous access. Performance not further tested. 
3. GraphQL allows to use a single query, but still requires ~40 seconds response time for IFC4.3 properties.

**Comment by MatthiasWeise** [comment]
It seems that our feature request has finally been accepted and will be available with the next update of the bSDD API. https://forums.buildingsmart.org/t/bsdd-tech-updates/4889/14, https://test.bsdd.buildingsmart.org/swagger/index.html
@atomczak and bSDD team: Many thanks for your support!

**Comment by Baars-IT** [comment]
The API api/Dictionary/v1/Properties is now available. It includes pagination options.
