### ISSUE TITLE
get API for the test domain 

### ISSUE THREAD

**Issue by nikilKaranjit** [buildingSMART/bSDD#38]
**Is your feature request related to a problem? Please describe.**
I  have uploaded my json file in the test domain but I need to verify  the data from the domain with my IFC file .As I have created a simple console application to compare the data with "get API " from the test domain and the data obtained from it will be compared to my IFC file .How can i get the aPI for the test domain to get all the classification

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Baars-IT** [comment]
Hi Nikilsss,

There is no API in which you get it all in one go (as that is against the nature of our API).
But what you can do for testing purposes, is first a call to the /api/Domain/v2/Classifications to get a list of all the classifications for the domain. And then for each classification you can do a call to /api/Classification/v3 (or v4, currently in test environment) to get all details of a classification.

**Comment by nikilsss** [comment]
Hi 
thank you for the information I am using v4 for the test environment.I have one question regarding documentation . Is the older documentation removed where there was table with detail information regarding the classification ,property.That was very helpful.

**Comment by Baars-IT** [comment]
Hi Nikil,

Not sure what you mean by “older documentation” but no documentation has been removed.
Do you mean this document: https://github.com/buildingSMART/bSDD/blob/master/Model/Import%20Model/bSDD%20JSON%20import%20model.md ?

Kind regards,
Erik
