### ISSUE TITLE
IFC attributes

### ISSUE THREAD

**Issue by Judithlourde** [buildingSMART/bSDD#48]
Is it possible to get Ifc attributes from bsDD?
When I am fetching data for example:
https://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/class/ifcDoor. It gives properties like Pset, Qto, and Attributes. But attributes do not contain names, owner history, and so on.

**Comment by atomczak** [comment]
@Judithlourde, sorry for the late reply, but could you describe the issue better? The bSDD dictionary of IFC contains properties and attributes, such as https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcDoor/prop/Attributes/OverallHeight. What else are you missing? Remember that bSDD is not the platform for publishing IFC schema, only the data dictionary. The documentation of IFC4.3 can be found here: https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcDoor.htm

**Comment by Judithlourde** [comment]
@atomczak, Thanks for your reply. My question is about getting the "attributes" from API. When I am getting classifications from API (https://test.bsdd.buildingsmart.org/swagger/index.html) for example https://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/class/ifcdoor, getting pset, qto, attributes here. But why am I not getting a "name", "OwnerHistory", "GlobalId" and "Description" under the attributes? 
Should that be called separately from ifcroot?

**Comment by atomczak** [comment]
Those are not defined in bSDD. The bSDD is not a platform to publish the whole IFC schema; it just contains the IFC data dictionary without relations etc. We will be improving the IFC content in bSDD later this year (adding missing predefined types, improving relations, and perhaps also translations). We could add those attributes as well, but can you better explain the use case for it? Why would you like to see those in bSDD?

**Comment by Judithlourde** [comment]
Thanks! 
I wanted to get all attributes under the classification in one call for getting the relation.

**Comment by atomczak** [comment]
Hi @Judithlourde, the new IFC 4.3 dictionary in bSDD contains attributes as well!
