### ISSUE TITLE
Fraction

### ISSUE THREAD

**Issue by ciroraggio** [buildingSMART/bSDD#49]
Hi, 

I have a question about the 'Fraction' field. Can it be set for all relation types (One of: HasMaterial, HasReference, IsEqualTo, IsSynonymOf, IsParentOf, IsChildOf, HasPart) or only for some?

Thanks.

**Comment by VladimirAlexiev** [comment]
Reading the description
> Optional provision of a fraction of the total amount (e.g. volume or weight) that applies to the Classification owning the relations. The sum of Fractions per classification/relationtype must be 1. Similar to Fraction in [IfcMaterialConstituent](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMaterialConstituent.htm)

it would appear to apply to `HasMaterial` only.

**Comment by Baars-IT** [comment]
It applies to all relation types: "The sum of Fractions per classification/relationtype must be 1".
The reference to IfcMaterialConstituent is just an example.

**Comment by VladimirAlexiev** [comment]
So @Baars-IT what is the meaning of Fraction for relations other than HasMaterial?
