### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by VitalijTetervov** [buildingSMART/bSDD#56]
Provided link does not work

1. Go to '[bSDD](https://github.com/buildingSMART/bSDD/tree/master)/[Documentation](https://github.com/buildingSMART/bSDD/tree/master/Documentation)
/bSDD JSON import model.md
2. Scroll down to ClassificationProperty -> PropertyNamespaceUr
3. 2. Click on http://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/prop/position 
5. See error

The link should provide reference property samples.

**Comment by atomczak** [comment]
Thanks @VitalijTetervov. That was supposed to be just an example, not an actual link, but after your remark I changed that to actual link: https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/prop/ClearWidth
