### ISSUE TITLE
Materials vs Classifications

### ISSUE THREAD

**Issue by lemoinet** [buildingSMART/bSDD#57]
What is the difference between Materials and Classifications in the bSDD JSON import model

Wouldn't it be easier to treat Materials as Classifications with ClassificationType=Material?
Because as stated in the documentation "A Material is similar to a Classification."

It also resolves immediately "Please note that the "code" of both Material(s) and Classification(s) must be unique within the domain. You can't have a Domain with Material with code "abcd" and a Classification with the same code "abcd"."

**Comment by atomczak** [comment]
@lemoinet yes, that is true. We already discussed that on forums (https://forums.buildingsmart.org/t/changes-to-bsdd-data-model-names/4753) and at workshops and that change has already been pushed to test, waiting to be deployed on production. For few months we will support both old and new approach.
