### ISSUE TITLE
Wrong encoding in RDF/XML

### ISSUE THREAD

**Issue by lemoinet** [buildingSMART/bSDD#60]
When you request [https://test.bsdd.buildingsmart.org/uri/pdt/pdt-1.0/class/suspendedceilingkit](https://test.bsdd.buildingsmart.org/uri/pdt/pdt-1.0/class/suspendedceilingkit) with Accept header equals to "application/rdf+xml", the output contains:

```xml
<?xml version="1.0" encoding="utf-16"?>
````
But the document is actually in utf-8 instead of utf-16

Change the encoding in RDF/XML from utf-16 to utf-8

**Comment by Baars-IT** [comment]
Appears to be a small bug in the dotNetRDF library we're using.
Applied a work-around to fix it, will be put into production soon.
