### ISSUE TITLE
Property status value change

### ISSUE THREAD

**Issue by ollyhensby** [buildingSMART/bSDD#62]
**Describe the bug**
The `status` value related to a Property has changed.

Before it was defined as either `active` or `inactive`:

https://github.com/buildingSMART/bSDD/blob/6ebb8fe92589e93bbae749813397f91cc5dab849/Documentation/bSDD%20JSON%20import%20model.md?plain=1#L157

Whereas now an integer value (as a string) is returned:
![image](https://github.com/buildingSMART/bSDD/assets/79875276/64bcd503-7d8a-4219-b8e6-6e659b6d165e)

**Question**
What do these values represent? My assumption is that 1: active; 2: inactive; 3: ???

**Comment by atomczak** [comment]
Thanks, I'm actually not sure. @Erik-RN, can you please clarify this?

**Comment by Baars-IT** [comment]
Ah, that's a bug indeed.
But it's fixed now. It returns "Preview", "Active" or "Inactive" again.
