### ISSUE TITLE
Transfer the translation for de-DE into this repository and upstream it into bSDD and on http://www.buildingsmart-tech.org

### ISSUE THREAD

**Issue by klacol** [buildingSMART/bSDD#7]
Based on the workflow, described in #2, the german translation of the PSets shall be contributed via this issue.

**Comment by klacol** [comment]
The PSetManager ist now turned on. The tool is transferring the approved PSets from the master branch into the bSDD.

I start the testing with this environment:

Targetserver: http://test.bsdd.buildingsmart.org
Test-PSet: PSets\YAML\Pset_ActionRequest.YAML

The results shall show up here:
http://test.bsdd.buildingsmart.org/#concept/browse/3KhIU0qRmHuO00025QrE$V

Any feedback is appreciated.

**Comment by klacol** [comment]
Yes, it workes. My test changes from this [commit](https://github.com/buildingSMART/bSDD/commit/b2c52f06c7254f6e4f06b3461583d5f644d3c142) are transferred to the testserver of the bSDD.

**Comment by klacol** [comment]
Ok, the PSetManager ist now activated for all PSets and runs against the test server of the bSDD: http://test.bsdd.buildingsmart.org.

I takes one hour to check 274 of 419 PSets. After this time, the Appveyor builds terminates, since the build time for all Appveyor builds are limited to 60 Minutes.

One open question is, if the content of the http://test.bsdd.buildingsmart.org is identical with http://bsdd.buildingsmart.org or not. I will ask @chiholau to clarify this.

**Comment by klacol** [comment]
Ok, the first run has just finished without exceptions:

Published 419 PSets with 2428 Properties.
in 44:19 minutes
for one language

@mirbekbekboliev : Please read [the log](https://ci.appveyor.com/project/klacol/bsdd). We have some work to do until Düsseldorf.

**Comment by klacol** [comment]
I have added some statistics in the log of the PSetManager:

Published 419 PSets with 2428 Properties.
This are together 5694 terms:
* 419 Psets each with a name and a definition (838 terms)
* 2428 Properties each with a name and a definition (4856 terms)

From these 5694 terms are 1890 translations missing into de-DE. And for 43 Properties the GUID's are missing in the YAML files. In these Properties are probably more translations missing.

Just some statistics, to know, what is to do, to translate one language.

**Comment by klacol** [comment]
I have fixed all GUID's in the YAML-PSets, that I could find in the bSDD (I have married them).

For these eight properties, I could not find any concept:

* Pset_ElectricFlowStorageDeviceTypeCommon.ModuleCapacity:
* Pset_ElectricFlowStorageDeviceTypeCommon.ModulesInParallel
* Pset_ElectricFlowStorageDeviceTypeCommon.ModulesInSeries
* Pset_ElectricFlowStorageDeviceTypeCommon.RadiativeFraction
* Pset_SolarDeviceTypeCommon.ActiveCellSurfaceAreaFraction
* Pset_SolarDeviceTypeCommon.CellEfficiency
* Pset_TransformerTypeCommon.EfficiencyCurve
* Pset_TransformerTypeCommon.RadiativeFraction

These eight concepts have to be created in the context of IFC4 (MSG). I will extend the PSetManager with this functionality.

**Comment by TLiebich** [comment]
those properties are partially identical to those added in IFC4 Add2 TC1. See
http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/link/4021-properties.htm

but only partially - need to find out why e.g. the reinforcing bar/mesh/tendom attributes, that are also new, are not listed.

**Comment by klacol** [comment]
> but only partially - need to find out why e.g. the reinforcing bar/mesh/tendom attributes, that are also new, are not listed.

Yes, my remarks are based on the checks against the content on http://test.bsdd.buildingsmart.org . This content seems to be not 100% identical with the content in http://bsdd.buildingsmart.org . We have to wait, what @chiholau  sais. 

Otherwise, we will just fix it and create the missing concepts in the context `IFC-2x4`.

**Comment by klacol** [comment]
Workes! This typo fix

![image](https://user-images.githubusercontent.com/10479772/52571274-8f026300-2e15-11e9-85b0-c74aee8124d4.png)

is now automatically corrected here:

![image](https://user-images.githubusercontent.com/10479772/52571340-aa6d6e00-2e15-11e9-80bc-86197ed08316.png)

:-)
