### ISSUE TITLE
Material Properties

### ISSUE THREAD

**Issue by TZwielehner** [buildingSMART/bSDD#72]
**Describe the bug**
The Excel template only allows to add properties to classifications, not to materials.

**Expected behavior**
The data model says that properties can be assigned to materials too.

**Comment by atomczak** [comment]
Hi @TZwielehner, we just had a long-awaited refactoring of the data model. You can read about all the changes on our notification board here: https://forums.buildingsmart.org/t/bsdd-tech-updates/4889/16

One of the changes was to treat materials as only a type of a class, not a separate concept. While we already updated the data model, we are yet to update the Excel template and python converter. You can find the new Excel template on temporary "excel_importer" branch, and we will soon update the python script too.  https://github.com/buildingSMART/bSDD/tree/excel_importer/Model/Import%20Model/spreadsheet-import 

You can continue using the Excel you got, as we support both previous and new data models. However, we will not fix the issue with the old template, instead advise to use the new one.

**Comment by atomczak** [comment]
The new Excel template and python script for converting Excel to JSON are now available on the master branch:
https://github.com/buildingSMART/bSDD/tree/master/Model/Import%20Model/spreadsheet-import
