### ISSUE TITLE
More documentation on "Property inheritance" (file bSDD JSON import model.md)

### ISSUE THREAD

**Issue by gverduci** [buildingSMART/bSDD#74]
In the first case *Parent `Class` → child `Class`* 
the documentation states:

The child `Class` does not inherit properties from the parent `Class`. If authors want child classes to also have properties of parent classes, **they should specify them intentionally in import files**.  

Is it possible to improve the bolded part, with more information about how the author should act?

**Comment by atomczak** [comment]
If you want the child class to inherit properties of class(es) above in the hierarchy, right now, the only way to do that is to list all of those properties in your input file manually. The import mechanism does not look at the properties of the parent. In other words: we do not resolve inheritance, all properties need to be added to classes by the author of a data dictionary.
