### ISSUE TITLE
Dynamic properties

### ISSUE THREAD

**Issue by TZwielehner** [buildingSMART/bSDD#76]
**Is your feature request related to a problem? Please describe.**
Please provide an explanation about how dynamic properties should be defined. Functions? Formulas?

**Describe the solution you'd like**
Example in Excel template, documentation

**Comment by atomczak** [comment]
Hi @TZwielehner

This peculiarity comes straight from the ISO23386:2020:
![image](https://github.com/buildingSMART/bSDD/assets/22922395/640931d3-199c-4e5e-a343-2d0e2df13509)

And we implemented it to be compliant with the ISO, but I have never seen anyone using it in practice (or software capable of interpreting it). 🤷‍♂️

PA031 'Dynamic property' in bSDD: 'IsDynamic' takes a boolean. 
PA032 'Parameters of the dynamic property' in bSDD: 'DynamicParameterPropertyCodes' takes a list of codes of properties.

The example (how I see it):

> _Properties: P1 (distance), P2 (time), P3 (speed)._ 
> _P3.IsDynamic: true_
> _P3.DynamicParameterPropertyCodes: [P1,P2]_
> _It says that value of P3 depend on P1 and P3, but it doesn't say that the formula is speed=distance/time._

Perhaps @grandfr or @Erik-RN you have a better idea of how to use dynamic properties?
