### ISSUE TITLE
Show all properties generates wrong url's for the additional properties

### ISSUE THREAD

**Issue by lemoinet** [buildingSMART/bSDD#84]
**Describe the bug**
When you click on the "Show all properties" link on the overview page of a dictionary, the additional properties all have a wrong url.

**To Reproduce**
1. Go to https://search.bsdd.buildingsmart.org/uri/LCA/LCA/3.0
2. Click on 'Show all properties'
3. Click on an additional property https://search.bsdd.buildingsmart.org/uri/LCA/LCA/3.0/class/organisationsauthorisedbytheEPDownerstousetheEPDda 
4. See error 'Sorry, cannot find the requested resource'

**Expected behavior**
The url should not be this https://search.bsdd.buildingsmart.org/uri/LCA/LCA/3.0/class/organisationsauthorisedbytheEPDownerstousetheEPDda but this https://search.bsdd.buildingsmart.org/uri/LCA/LCA/3.0/prop/organisationsauthorisedbytheEPDownerstousetheEPDda

**Comment by atomczak** [comment]
Thanks for reporting this glitch on the search page - indeed, the page was generating the wrong URLs. It has been resolved.
