### ISSUE TITLE
bsdd API: URI example not working

### ISSUE THREAD

**Issue by ollyhensby** [buildingSMART/bSDD#87]
**Describe the bug**
Example URI in the Class API call does not work:

`https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.1/class/apple`

![image](https://github.com/buildingSMART/bSDD/assets/79875276/4ffda504-62e8-4cdb-89de-eee5cb63902a)

![image](https://github.com/buildingSMART/bSDD/assets/79875276/0ee689da-6378-4e65-8113-74601de35a2d)

Appears to work with the URI `https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.0.0/class/apple` so maybe it is an issue with the version?

**Comment by atomczak** [comment]
Indeed, that was related to the version. We now added missing version and the page should return valid response. Thank you for spotting that.
