### ISSUE TITLE
❔ Property Inheritance

### ISSUE THREAD

**Issue by ollyhensby** [buildingSMART/bSDD#91]
**Describe the bug**
It mentions [here](https://github.com/buildingSMART/bSDD/blob/master/Documentation/bSDD%20JSON%20import%20model.md#property-inheritance) in the documentation that `The child Class does not inherit properties from the parent Class`.

This statement is then followed by this example:

For example, the [IfcWall](https://search.bsdd.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall) is a parent class of [IfcWallStandardCase](https://search.bsdd.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWallStandardCase). While [IfcWall](https://search.bsdd.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall) has the property [AcousticRating](https://search.bsdd.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall/prop/Pset_WallCommon/AcousticRating), the [IfcWallStandardCase](https://search.bsdd.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWallStandardCase) doesn't.

It seems [IfcWallStandardCase](https://search.bsdd.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWallStandardCase) doesn't exist anymore in [IFC 4.3](https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3) so I have tried to check the example using [IfcWallSTANDARD](https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWallSTANDARD) instead. It appears that [IfcWallSTANDARD](https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWallSTANDARD) does contain the property [Acoustic Rating](https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/prop/AcousticRating).

So, is it still true that child classes do not inherit properties from their parent class? Or is it that the example needs updating? 

Also, just wanted to add that the new bsdd API is great so thank you for the great work on that!

**To Reproduce**
Steps to reproduce the behaviour:

I've used the bsdd api to obtain the class properties for each class and then find the set difference between the two:
```python
import requests

URL = lambda ifc_class: f"https://api.bsdd.buildingsmart.org/api/Class/v1?Uri=https%3A%2F%2Fidentifier.buildingsmart.org%2Furi%2Fbuildingsmart%2Fifc%2F4.3%2Fclass%2F{ifc_class}&IncludeClassProperties=true"

# Obtain data from bsdd api
response = requests.get(URL("IfcWall"))
ifc_wall = response.json()
response = requests.get(URL("IfcWallSTANDARD"))
ifc_wall_standard_case = response.json()

# Get sets of property names for each class
ifc_wall_property_names = set([property_["name"] for property_ in ifc_wall["classProperties"]])
ifc_wall_standard_case_property_names = set([property_["name"] for property_ in ifc_wall_standard_case["classProperties"]])

# I would expect this set difference between the properties to return AcousticRating
print(ifc_wall_property_names - ifc_wall_standard_case_property_names)
```

**Comment by atomczak** [comment]
@ollyhensby the bSDD doesn't automatically inherit properties. You see the same property in both parent/child element, because it was explicitly defined in the upload. This shifts the effort from the software interpreting bSDD to the admin publishing in bSDD.
